# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ak_clip.py
# Created on: 2016-08-29 14:46:20.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Clips state wide Incplace file to a specfic county file by FIPS.  Set up currently for local alaska data
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


#loop
xList = [ "198", "240", "261", "270", "290"] 
print "start loop"

for x in xList:

# Local variables:
    #local incplace data with path
    City_Boundaries = "\\\\batch4.ditd.census.gov\\mtdata003_geoarea\\BAS\\CARP\\BQARP\\02\\For NPC\\bqarp_2016_02_incplace_v90.shp"
    #local county data
    local_borough_02013_shp = "\\\\batch4.ditd.census.gov\\mtdata003_geoarea\\BAS\\CARP\\BQARP\\02\\For NPC\\02"+x+"\\bqarp_2016_02"+x+"_county_v90.shp"
    #output of local incplace data at a county level. With output path included
    local_places_02013_shp = "\\\\batch4.ditd.census.gov\\mtdata003_geoarea\\BAS\\CARP\\BQARP\\02\\For NPC\\02"+x+"\\census_places_02"+x+".shp"
# Process: Clip
    arcpy.Clip_analysis(City_Boundaries, local_borough_02013_shp, local_places_02013_shp, "")

    print "Clipped "+ x + " places"
