# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# county_add_fields.py
# Created on: 2016-10-24 14:01:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: county_add_fields <County_Disrepancy_Layer> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
County_Disrepancy_Layer = arcpy.GetParameterAsText(0)
if County_Disrepancy_Layer == '#' or not County_Disrepancy_Layer:
    County_Disrepancy_Layer = "County Disrepancy Layer" # provide a default value if unspecified

# Local variables:
Output_Feature_Class = County_Disrepancy_Layer
Output_Feature_Class__7_ = Output_Feature_Class
Output_Feature_Class__4_ = Output_Feature_Class__7_
Output_Feature_Class__2_ = Output_Feature_Class__4_
Output_Feature_Class__5_ = Output_Feature_Class__2_
Output_Feature_Class__3_ = Output_Feature_Class__5_
Output_Feature_Class__6_ = Output_Feature_Class__3_
Output_Table = Output_Feature_Class__6_

# Process: Add Field - RELATE
arcpy.AddField_management(County_Disrepancy_Layer, "RELATE", "TEXT", "", "", "5", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - VERIFY
arcpy.AddField_management(Output_Feature_Class, "VERIFY", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - V_COMMENTS
arcpy.AddField_management(Output_Feature_Class__7_, "V_COMMENTS", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - DIGITIZE
arcpy.AddField_management(Output_Feature_Class__4_, "DIGITIZE", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - D_COMMENTS
arcpy.AddField_management(Output_Feature_Class__2_, "D_COMMENTS", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - DIG_QA
arcpy.AddField_management(Output_Feature_Class__5_, "DIG_QA", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Q_COMMENTS
arcpy.AddField_management(Output_Feature_Class__3_, "Q_COMMENTS", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Delete Field - NAME_1
arcpy.DeleteField_management(Output_Feature_Class__6_, "NAME_1")

