# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# county_split.py
# Created on: 2016-08-25 13:18:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Splits a single statewide county file into a bunch of county based county file by county FIPS code
#This code is kind of stupid because it does the same thing twice.Once for Census counties and once for local. Census is grayed out for now. 
# ---------------------------------------------------------------------------


# Import arcpy module
import arcpy

# Local variables:
# inPath is the location of the original statewide county data file
inPath = "\\\\batch4.ditd.census.gov\\mtdata003_geoarea\\BAS\\CARP\\BQARP\\02\\Census Data\\"
#outPath is the location of where the individual county data will go
outPath = "\\\\batch4.ditd.census.gov\\mtdata003_geoarea\\BAS\\CARP\\BQARP\\02\\For NPC\\"
#inPath is a different location of the original statewide county data file
inPath2 = "\\\\It172oafs-oa10\\HOME_S\\sovic002\\ArcGIS\\Default.gdb\\"
#loop
xList = ["282", "275", "100", "105", "130", "230", "185", "195", "198", "240", "261", "290"]  
print "start loop"

for x in xList:
# Local variables:
#    census_counties = inPath + "bqarp_2016_38_county_v90.shp"
#    census_county_x = outPath + "census_county_38"+x+".shp"
    local_counties = inPath2 + "c02016_Final_Merge"
    local_county_x = outPath + "02"+x+"\\local_borough_02"+x+"_ne.shp"

# Process: Select
#    arcpy.Select_analysis(census_counties, census_county_x, "\"COUNTYFP\" = '001'")
 #   print "Census county "+ x + " made"

# Process: Select (2)
    arcpy.Select_analysis(local_counties, local_county_x, "COUNTYFP = '"+x+"'")
    print "Local county "+ x + " made"
