__author__ = 'Maddie Sovich'
__author__ = 'Lauren Makely'

# ---------------------------------------------------------------------------
# MS_split_discrepancies.py
# Created on: 2016-03-10 13:06:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Splits a premade statewide county discrepancy file into county sized chunks by the county FIPS code. 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# import this from core/stcou.py
# start for loop (County FIPS codes in the state)
# xList = ["013", "020", "060", "068", "090", "100", "110", "122", "130", "150", "164", "170", "185", "188", "195", "220", "230", "275", "282","198", "240", "261", "270", "290"]


def split_discrepancies(st_cou_list, discrep_shp_path):
    """
    :param st_cou_list:         import this list of county codes from the core/stcou.py dictionaries or input a list of
                                them.
    :param discrep_shp_path:    path to the discrepancy shapefile previously created. also pulls the directory name to
                                build a path to workspace
    """
    print "start loop"

    # The Loop Begins
    for cou in st_cou_list:
        print cou

    # Local variables:
    #   Statewide county discrepancy shapefile
        discrepancies_counties_51 = "\\\\batch4.ditd.census.gov\\mtdata003_geoarea\\BAS\\CARP\\BQARP\\02\\discrepancies_counties_3.shp"
    #   variable for the Make a Feature Layer placeholder
        discrepancies_counties_51_La = "discrepancies_counties_51_La"
    #   Uh, redundancy I guess? A variable of a variable?
        discrepancies_counties_51_La__4_ = discrepancies_counties_51_La

    #   SQL Expression for selecting the discrepancies in a county.  All discrepancies with and local FIPS code of cou
    #   OR a Census FIPS code of cou. millage may vary on the attribute names
        SQL_Expression = """ "COUNTYFP" = '{0}' OR "COUNTYFP_1" = '{0}' """.format(cou)
    #   Output of the county
        discrepancies_county_51005_shp = "\\\\batch4.ditd.census.gov\\mtdata003_geoarea\\BAS\\CARP\\BQARP\\02\\For NPC\\02"+cou+"\\discrepancies_county_02"+cou+".shp"
        discrepancies_counties_51_La__3_ = discrepancies_counties_51_La__4_

    # Process: Make Feature Layer
        try:
            arcpy.MakeFeatureLayer_management(discrepancies_counties_51, discrepancies_counties_51_La, "", "")
            print "Made Feature Layer"
        except Exception as e:
            print e.message
    # Process: Select
        try:
             arcpy.Select_analysis(discrepancies_counties_51_La, discrepancies_county_51005_shp, SQL_Expression)
             print "Select analysis for copy "+cou
        except Exception as e:
            print e.message
    # Process: Select Layer By Attribute
        try:
            arcpy.SelectLayerByAttribute_management(discrepancies_counties_51_La, "NEW_SELECTION", SQL_Expression)
            print "Select Layer to Delete"
        except Exception as e:
            print e.message
    # Process: Delete Features
        try:
            arcpy.DeleteFeatures_management(discrepancies_counties_51_La__4_)
            print "Delete successful"
        except Exception as e:
            print e.message
