# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# NPC_create_populate_gdb.py
# Created on: 2016-10-24 14:01:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: create_populate_gdb <File_GDB_Location> <File_GDB_Name> <Input_Features> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("H:/!!!HDriveStuff/BQARP/BQARP.tbx")

# Script arguments
File_GDB_Location = arcpy.GetParameterAsText(0)

File_GDB_Name = arcpy.GetParameterAsText(1)

Input_Features = arcpy.GetParameterAsText(2)

# Local variables:
Output_File_GDB = File_GDB_Location
Original_Shapefiles = File_GDB_Location
Folder_Name = "original_shapefiles"
Derived_Geodatabase = Output_File_GDB

# Process: Create File GDB
arcpy.CreateFileGDB_management(File_GDB_Location, File_GDB_Name, "CURRENT")

# Process: Feature Class to Geodatabase (multiple)
arcpy.FeatureClassToGeodatabase_conversion(Input_Features, Output_File_GDB)

# Process: Create Folder
tempEnvironment0 = arcpy.env.workspace
arcpy.env.workspace = Derived Geodatabase
arcpy.CreateFolder_management(File_GDB_Location, Folder_Name)
arcpy.env.workspace = tempEnvironment0

# Process: Move Original Shps
arcpy.gp.toolbox = "H:/!!!HDriveStuff/BQARP/BQARP.tbx";
# Warning: the toolbox H:/!!!HDriveStuff/BQARP/BQARP.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.MoveOriginals(...) with arcpy.MoveOriginals_ALIAS(...)
arcpy.gp.MoveOriginals(Input_Features, Original_Shapefiles)

