# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# NPC_county_add_fields.py
# Created on: 2016-10-24 14:01:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: county_add_fields <County_Discrepancy_Layer>
# Description: adds required QC fields.
#
# To Do:
#   - format as function(fc_to_modify)
#
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
County_Discrepancy_Layer = arcpy.GetParameterAsText(0)
if County_Discrepancy_Layer == '#' or not County_Discrepancy_Layer:
    County_Discrepancy_Layer = "County Discrepancy Layer"  # provide a default value if unspecified

# Process: Add Field - RELATE
arcpy.AddField_management(County_Discrepancy_Layer, "RELATE", "TEXT", field_length="5",)

# Process: Add Field - VERIFY
arcpy.AddField_management(County_Discrepancy_Layer, "VERIFY", "TEXT", field_length="1")

# Process: Add Field - V_COMMENTS
arcpy.AddField_management(County_Discrepancy_Layer, "V_COMMENTS", "TEXT", field_length="100")

# Process: Add Field - DIGITIZE
arcpy.AddField_management(County_Discrepancy_Layer, "DIGITIZE", "TEXT", field_length="1")

# Process: Add Field - D_COMMENTS
arcpy.AddField_management(County_Discrepancy_Layer, "D_COMMENTS", "TEXT", field_length="100")

# Process: Add Field - DIG_QA
arcpy.AddField_management(County_Discrepancy_Layer, "DIG_QA", "TEXT", field_length="1")

# Process: Q_COMMENTS
arcpy.AddField_management(County_Discrepancy_Layer, "Q_COMMENTS", "TEXT", field_length="100")

# Process: Delete Field - NAME_1
arcpy.DeleteField_management(County_Discrepancy_Layer, "NAME_1")