# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# NPC_selection_test_2.py
# Created on: 2016-10-24 14:03:42.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: selection_test_2 <Layer_Name_or_Table_View> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Layer_Name_or_Table_View = arcpy.GetParameterAsText(0)

# Local variables:
Output_Layer_Name = Layer_Name_or_Table_View
Delete_succeeded = "false"

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(Layer_Name_or_Table_View, "NEW_SELECTION", "TOWN = ' ' OR NAME = ' '")

# Process: Delete
arcpy.Delete_management(Output_Layer_Name, "")

