# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# selection_test.py
# Created on: 2016-11-04 16:05:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
local_places_projected_shp = "H:\\!!!HDriveStuff\\BQARP\\20\\projected_local\\local_places_projected.shp"
local_places_projected_Layer1 = "local_places_projected_Layer1"
Output_Layer_Name__2_ = local_places_projected_Layer1
local_joined_shp = "H:\\!!!HDriveStuff\\BQARP\\20\\projected_local\\local_joined.shp"
local_joined_Layer1 = "local_joined_Layer1"
local_joined_Layer1__2_ = local_joined_Layer1
projected_local = "H:\\!!!HDriveStuff\\BQARP\\20\\projected_local"
test_shp = "H:\\!!!HDriveStuff\\BQARP\\20\\projected_local\\test.shp"

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(local_places_projected_shp,
                                  local_places_projected_Layer1,
                                  "",
                                  "",
                                  "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;STEWARD STEWARD VISIBLE NONE;L_UPDATE L_UPDATE VISIBLE NONE;EFF_DATE EFF_DATE VISIBLE NONE;EXP_DATE EXP_DATE VISIBLE NONE;MUNI_ID MUNI_ID VISIBLE NONE;STATE STATE VISIBLE NONE;COUNTY COUNTY VISIBLE NONE;MUNI MUNI VISIBLE NONE;UPDATEBY UPDATEBY VISIBLE NONE;SHAPE_LENG SHAPE_LENG VISIBLE NONE;SUBMIT SUBMIT VISIBLE NONE;NOTES NOTES VISIBLE NONE;SCALE SCALE VISIBLE NONE;SOURCE SOURCE VISIBLE NONE;KS_UPDATE KS_UPDATE VISIBLE NONE;Shape_Le_1 Shape_Le_1 VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE")

# Process: Make Feature Layer (2)
arcpy.MakeFeatureLayer_management(local_joined_shp,
                                  local_joined_Layer1,
                                  "",
                                  "",
                                  "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;Join_Count Join_Count VISIBLE NONE;TARGET_FID TARGET_FID VISIBLE NONE;MTDBOID MTDBOID VISIBLE NONE;STATEFP STATEFP VISIBLE NONE;COUNTYFP COUNTYFP VISIBLE NONE;VINTAGE VINTAGE VISIBLE NONE;MTFCC MTFCC VISIBLE NONE;NAME NAME VISIBLE NONE;CLASSFP CLASSFP VISIBLE NONE;CBSAFP CBSAFP VISIBLE NONE;COUNTYFP5 COUNTYFP5 VISIBLE NONE;COUSUBTYP COUSUBTYP VISIBLE NONE;CSAFP CSAFP VISIBLE NONE;FUNCSTAT FUNCSTAT VISIBLE NONE;LSAD LSAD VISIBLE NONE;METDIVFP METDIVFP VISIBLE NONE;UR UR VISIBLE NONE;AREAWATER AREAWATER VISIBLE NONE;AREALAND AREALAND VISIBLE NONE;AREAWHIST AREAWHIST VISIBLE NONE;AREALHIST AREALHIST VISIBLE NONE;HOUSING HOUSING VISIBLE NONE;POPDEC POPDEC VISIBLE NONE;POPACS POPACS VISIBLE NONE;POPPEP POPPEP VISIBLE NONE;PERIM PERIM VISIBLE NONE;CYCLES CYCLES VISIBLE NONE;CYCLESMAX CYCLESMAX VISIBLE NONE;ESTABDATE ESTABDATE VISIBLE NONE;EFFDATE EFFDATE VISIBLE NONE;DISDATE DISDATE VISIBLE NONE;COUNTYNS COUNTYNS VISIBLE NONE;ROCE ROCE VISIBLE NONE;PLANREGCE PLANREGCE VISIBLE NONE;PLCREL PLCREL VISIBLE NONE;local_name local_name VISIBLE NONE;COUNTY COUNTY VISIBLE NONE;OBJECTID OBJECTID VISIBLE NONE;STEWARD STEWARD VISIBLE NONE;L_UPDATE L_UPDATE VISIBLE NONE;COUNTYID COUNTYID VISIBLE NONE;STATE STATE VISIBLE NONE;COUNTY_1 COUNTY_1 VISIBLE NONE;UPDATEBY UPDATEBY VISIBLE NONE;SHAPE_Leng SHAPE_Leng VISIBLE NONE;SUBMIT SUBMIT VISIBLE NONE;NOTES NOTES VISIBLE NONE;Shape_Le_1 Shape_Le_1 VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE;SOURCE SOURCE VISIBLE NONE;KS_UPDATE KS_UPDATE VISIBLE NONE")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(local_joined_Layer1,
                                        "NEW_SELECTION",
                                        "\"COUNTYFP\" = '003'")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(local_places_projected_Layer1,
                                       "INTERSECT",
                                       local_joined_Layer1__2_,
                                       "",
                                       "NEW_SELECTION",
                                       "NOT_INVERT")

# Process: Feature Class to Feature Class
arcpy.FeatureClassToFeatureClass_conversion(Output_Layer_Name__2_,
                                            projected_local,
                                            "test.shp",
                                            "",
                                            "STEWARD \"STEWARD\" true true false 50 Text 0 0 ,First,#,local_places_projected_Layer1,STEWARD,-1,-1;L_UPDATE \"L_UPDATE\" true true false 8 Date 0 0 ,First,#,local_places_projected_Layer1,L_UPDATE,-1,-1;EFF_DATE \"EFF_DATE\" true true false 8 Date 0 0 ,First,#,local_places_projected_Layer1,EFF_DATE,-1,-1;EXP_DATE \"EXP_DATE\" true true false 8 Date 0 0 ,First,#,local_places_projected_Layer1,EXP_DATE,-1,-1;MUNI_ID \"MUNI_ID\" true true false 38 Text 0 0 ,First,#,local_places_projected_Layer1,MUNI_ID,-1,-1;STATE \"STATE\" true true false 2 Text 0 0 ,First,#,local_places_projected_Layer1,STATE,-1,-1;COUNTY \"COUNTY\" true true false 100 Text 0 0 ,First,#,local_places_projected_Layer1,COUNTY,-1,-1;MUNI \"MUNI\" true true false 100 Text 0 0 ,First,#,local_places_projected_Layer1,MUNI,-1,-1;UPDATEBY \"UPDATEBY\" true true false 50 Text 0 0 ,First,#,local_places_projected_Layer1,UPDATEBY,-1,-1;SHAPE_LENG \"SHAPE_LENG\" true true false 19 Double 0 0 ,First,#,local_places_projected_Layer1,SHAPE_LENG,-1,-1;SUBMIT \"SUBMIT\" true true false 1 Text 0 0 ,First,#,local_places_projected_Layer1,SUBMIT,-1,-1;NOTES \"NOTES\" true true false 254 Text 0 0 ,First,#,local_places_projected_Layer1,NOTES,-1,-1;SCALE \"SCALE\" true true false 5 Short 0 5 ,First,#,local_places_projected_Layer1,SCALE,-1,-1;SOURCE \"SOURCE\" true true false 100 Text 0 0 ,First,#,local_places_projected_Layer1,SOURCE,-1,-1;KS_UPDATE \"KS_UPDATE\" true true false 8 Date 0 0 ,First,#,local_places_projected_Layer1,KS_UPDATE,-1,-1;Shape_Le_1 \"Shape_Le_1\" true true false 19 Double 0 0 ,First,#,local_places_projected_Layer1,Shape_Le_1,-1,-1;Shape_Area \"Shape_Area\" true true false 19 Double 0 0 ,First,#,local_places_projected_Layer1,Shape_Area,-1,-1", "")

