# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ST53_field_cleanup.py
# Created on: 2016-10-24 14:04:00.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: ST53_field_cleanup <Input_Table> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_Table = arcpy.GetParameterAsText(0)

# Local variables:
Output_Feature_Class = Input_Table
Output_Feature_Class__2_ = Output_Feature_Class
Output_Table = Output_Feature_Class__2_

# Process: Add Field
arcpy.AddField_management(Input_Table, "NAME", "TEXT", "", "", "50", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Output_Feature_Class, "NAME", "[CITY_NM]", "VB", "")

# Process: Delete Field
arcpy.DeleteField_management(Output_Feature_Class__2_, "CITY_NM")

