__author__ = 'Maddie Sovich'
__author__ = 'Lauren Makely'

# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# step_2a_counties.py
# Created on: 2016-10-24 14:04:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: step_2a <Local_County_Layer> <Census_County_Layer> <Name_Fields__replace_CTYNAME_if_necessary_> <Temporary_Output_File> <Output_Discrepancy_File> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Local_County_Layer = arcpy.GetParameterAsText(0)
if Local_County_Layer == '#' or not Local_County_Layer:
    Local_County_Layer = "local_places_49001" # provide a default value if unspecified

Census_County_Layer = arcpy.GetParameterAsText(1)
if Census_County_Layer == '#' or not Census_County_Layer:
    Census_County_Layer = "census_places_49001" # provide a default value if unspecified

Name_Fields__replace_CTYNAME_if_necessary_ = arcpy.GetParameterAsText(2)
if Name_Fields__replace_CTYNAME_if_necessary_ == '#' or not Name_Fields__replace_CTYNAME_if_necessary_:
    Name_Fields__replace_CTYNAME_if_necessary_ = "CTYNAME <> NAME" # provide a default value if unspecified

Temporary_Output_File = arcpy.GetParameterAsText(3)
if Temporary_Output_File == '#' or not Temporary_Output_File:
    Temporary_Output_File = "R:\\CARP\\BQARP\\TestModel\\discrepancies_temp" # provide a default value if unspecified

Output_Discrepancy_File = arcpy.GetParameterAsText(4)
if Output_Discrepancy_File == '#' or not Output_Discrepancy_File:
    Output_Discrepancy_File = "C:\\Documents and Settings\\snedi001\\My Documents\\ArcGIS\\Default.gdb\\discrepancies" # provide a default value if unspecified

# Local variables:
county_union = "in_memory\\places_union"
counties_select = "in_memory\\places_select"
counties_select_Singlepart = "\\\\it172oafs-oa10\\HOME_S\\snedi001\\ArcGIS\\Default.gdb\\places_select_MultipartToSin"
discrepancies = Output_Discrepancy_File
places_union_Project__3_ = discrepancies
places_union_Project__2_ = places_union_Project__3_
discrepancies__2_ = places_union_Project__2_
discrepancies__3_ = discrepancies__2_
discrepancies__4_ = discrepancies__3_
places_union_Project__5_ = discrepancies__4_
Delete_succeeded = "false"

# Process: Union
arcpy.Union_analysis("local_places_49001 #;census_places_49001 #", county_union, "ALL", "", "GAPS")

# Process: Select
arcpy.Select_analysis(county_union, counties_select, Name_Fields__replace_CTYNAME_if_necessary_)

# Process: Multipart To Singlepart
arcpy.MultipartToSinglepart_management(counties_select, counties_select_Singlepart)

# Process: Project
arcpy.Project_management(counties_select_Singlepart, Temporary_Output_File, "PROJCS['North_America_Albers_Equal_Area_Conic',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Albers'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-96.0],PARAMETER['Standard_Parallel_1',20.0],PARAMETER['Standard_Parallel_2',60.0],PARAMETER['Latitude_Of_Origin',40.0],UNIT['Meter',1.0]]", "", "", "NO_PRESERVE_SHAPE", "")

# Process: Calculate Areas
arcpy.CalculateAreas_stats(Temporary_Output_File, Output_Discrepancy_File)

# Process: Add Field - DISC_ID
arcpy.AddField_management(Output_Discrepancy_File, "DISC_ID", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - MSP
arcpy.AddField_management(discrepancies, "MSP", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - PROCESS
arcpy.AddField_management(places_union_Project__3_, "PROCESS", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field- VERIFY
arcpy.AddField_management(places_union_Project__2_, "VERIFY", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - DIGITIZE
arcpy.AddField_management(discrepancies__2_, "DIGITIZE", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - DIG_QA
arcpy.AddField_management(discrepancies__3_, "DIG_QA", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - COMMENTS
arcpy.AddField_management(discrepancies__4_, "COMMENTS", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Delete
arcpy.Delete_management(Temporary_Output_File, "")

