# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# step_2a_places.py
# Created on: 2016-10-24 14:05:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: step_2a_places <Local_Place_Layer> <Census_Place_Layer> <Name_Fields__replace_PLACENAME_if_necessary_> <Temporary_Output_File> <Output_Discrepancy_File> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Local_Place_Layer = arcpy.GetParameterAsText(0)
if Local_Place_Layer == '#' or not Local_Place_Layer:
    Local_Place_Layer = "local_places_49001" # provide a default value if unspecified

Census_Place_Layer = arcpy.GetParameterAsText(1)
if Census_Place_Layer == '#' or not Census_Place_Layer:
    Census_Place_Layer = "census_places_49001" # provide a default value if unspecified

Name_Fields__replace_PLACENAME_if_necessary_ = arcpy.GetParameterAsText(2)
if Name_Fields__replace_PLACENAME_if_necessary_ == '#' or not Name_Fields__replace_PLACENAME_if_necessary_:
    Name_Fields__replace_PLACENAME_if_necessary_ = "NAME <> NAME_1" # provide a default value if unspecified

Temporary_Output_File = arcpy.GetParameterAsText(3)
if Temporary_Output_File == '#' or not Temporary_Output_File:
    Temporary_Output_File = "R:\\CARP\\BQARP\\TestModel\\discrepancies_temp" # provide a default value if unspecified

Output_Discrepancy_File = arcpy.GetParameterAsText(4)
if Output_Discrepancy_File == '#' or not Output_Discrepancy_File:
    Output_Discrepancy_File = "C:\\Documents and Settings\\snedi001\\My Documents\\ArcGIS\\Default.gdb\\discrepancies" # provide a default value if unspecified

# Local variables:
places_union = "in_memory\\places_union"
places_select = "in_memory\\places_select"
places_select_MultipartToSin = "in_memory\\places_select_MultipartToSin"
discrepancies__5_ = Output_Discrepancy_File
Delete_succeeded = "false"
discrepancies__12_ = discrepancies__5_
discrepancies = discrepancies__12_
discrepancies__2_ = discrepancies
discrepancies__10_ = discrepancies__2_
discrepancies__6_ = discrepancies__10_
discrepancies__7_ = discrepancies__6_
discrepancies__4_ = discrepancies__7_
discrepancies__8_ = discrepancies__4_
discrepancies__3_ = discrepancies__8_
discrepancies__9_ = discrepancies__3_
discrepancies__11_ = discrepancies__9_

# Process: Union
arcpy.Union_analysis("local_places_49001 #;census_places_49001 #", places_union, "ALL", "", "GAPS")

# Process: Select
arcpy.Select_analysis(places_union, places_select, Name_Fields__replace_PLACENAME_if_necessary_)

# Process: Multipart To Singlepart
arcpy.MultipartToSinglepart_management(places_select, places_select_MultipartToSin)

# Process: Project
arcpy.Project_management(places_select_MultipartToSin, Temporary_Output_File, "PROJCS['North_America_Albers_Equal_Area_Conic',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Albers'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-96.0],PARAMETER['Standard_Parallel_1',20.0],PARAMETER['Standard_Parallel_2',60.0],PARAMETER['Latitude_Of_Origin',40.0],UNIT['Meter',1.0]]", "", "", "NO_PRESERVE_SHAPE", "")

# Process: Calculate Areas
arcpy.CalculateAreas_stats(Temporary_Output_File, Output_Discrepancy_File)

# Process: Delete
arcpy.Delete_management(Temporary_Output_File, "")

# Process: FEEDBACK
arcpy.AddField_management(Output_Discrepancy_File, "FEEDBACK", "TEXT", "", "", "3", "", "NULLABLE", "NON_REQUIRED", "")

# Process: COMMENTS
arcpy.AddField_management(discrepancies__5_, "COMMENTS", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - RELATE
arcpy.AddField_management(discrepancies__12_, "RELATE", "TEXT", "", "", "5", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - PROCESS
arcpy.AddField_management(discrepancies, "PROCESS", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - P_COMMENTS
arcpy.AddField_management(discrepancies__2_, "P_COMMENTS", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - VERIFY
arcpy.AddField_management(discrepancies__10_, "VERIFY", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - V_COMMENTS
arcpy.AddField_management(discrepancies__6_, "V_COMMENTS", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - DIGITIZE
arcpy.AddField_management(discrepancies__7_, "DIGITIZE", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - D_COMMENTS
arcpy.AddField_management(discrepancies__4_, "D_COMMENTS", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - DIG_QA
arcpy.AddField_management(discrepancies__8_, "DIG_QA", "TEXT", "", "", "1", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field - Q_COMMENTS
arcpy.AddField_management(discrepancies__3_, "Q_COMMENTS", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Delete Field - NAME_1
arcpy.DeleteField_management(discrepancies__9_, "NAME_1")

